import { parseIvrTimestamp } from './ivrAnalyzer'
import type { VoiceCall, VoiceEvent, VoiceExtensionAnalysis } from './types'

export function normalizeEfrontVoiceRecords(text:string){return text.split(/\r?\n|(?=\d{4}-\d{2}-\d{2}\s+\d{2}:\d{2}:\d{2},\d{3})/).map(x=>x.trim()).filter(Boolean)}
function field(line:string,name:string){return line.match(new RegExp(`\\b${name}\\s*[=:]\\s*['"]?([^,}\\s'"]+)`,'i'))?.[1]}
function caller(line:string){return line.match(/\[\d{8,}\]\s*\[\d+\]\s*\[(\d{7,})\]/)?.[1]??field(line,'callerid')??line.match(/caller id\s*:\s*(\d{7,})/i)?.[1]}
function callId(line:string){return line.match(/\[(\d{12,})\]\s*\[\d+\]\s*\[\d{7,}\]/)?.[1]??field(line,'callid')}
function voiceEvent(line:string,n:number):VoiceEvent|undefined{const p=parseIvrTimestamp(line);const base={timestamp:p?.timestamp,timestampMs:p?.timestampMs,lineNumber:n,rawLine:line}
 const make=(type:VoiceEvent['type'],label:string)=>({...base,type,label})
 if(/addCallTransaction|addTransaction\(\).*inserted/i.test(line))return make('CALL_CREATED','Call Transaction Created')
 if(/CONFIRMAGTBOOKING_RSP\|OK/i.test(line))return make('AGENT_BOOKED','Agent Booking Confirmed')
 if(/GETAVAILAGT|getAvailableAgent/i.test(line))return make('AGENT_SEARCH','Searching for available Agent')
 if(/UPDATECALLTRANSACTION|agentExtension\s*:/i.test(line))return make('ROUTE_TO_AGENT','Route to Agent')
 if(/ExtensionStatusEvent.*Ringing|statustext=['"]Ringing|DialEvent|connectionAlerting|Incoming call/i.test(line))return make('AGENT_RINGING','Agent Ringing')
 if(/connectionEstablished|Call connected|callConnected\(|talkstart=(?!null)/i.test(line))return make('CALL_CONNECTED','Call Connected')
 if(/callDisconnected\(|talkend=(?!null)/i.test(line))return make('CALL_DISCONNECTED','Call Disconnected')
 if(/MusicOnHoldEvent|calculated hold duration/i.test(line))return make('CALL_HOLD','Call Hold')
 if(/ERROR|Exception/i.test(line))return make('ERROR','Error')
}
export function analyzeVoiceCalls(records:string[]):VoiceCall[]{const m=new Map<string,VoiceCall>();let activeId:string|undefined,activeCaller:string|undefined
 records.forEach((line,i)=>{activeId=callId(line)??activeId;activeCaller=caller(line)??activeCaller;if(!activeId||!activeCaller)return;const c=m.get(activeId)??{callerId:activeCaller,callId:activeId,events:[],agentSearchAttempts:0,routingStatus:'Unknown',callStatus:'Unknown',problemScore:0};c.callerId=caller(line)??c.callerId
 c.transactionId=line.match(/(?:[,{]\s*)id\s*=\s*(\d+)/i)?.[1]??c.transactionId;c.campaignId=field(line,'campaignid')??line.match(/campaign\s*:\s*(\d+)/i)?.[1]??c.campaignId;c.agentGroupId=line.match(/agent group\s*:\s*(\d+)/i)?.[1]??c.agentGroupId;c.agentId=field(line,'agentid')??line.match(/UPDATECALLTRANSACTION\|(\d+)\|/i)?.[1]??c.agentId;c.extension=line.match(/CONFIRMAGTBOOKING_RSP\|OK\|(\d+)/i)?.[1]??line.match(/UPDATECALLTRANSACTION\|\d+\|(\d+)/i)?.[1]??field(line,'deviceno')??field(line,'agentExtension')??c.extension
 c.routeStart=field(line,'routestart')??c.routeStart;c.routeEnd=field(line,'routeend')??c.routeEnd;c.talkStart=field(line,'talkstart')??c.talkStart;c.talkEnd=field(line,'talkend')??c.talkEnd;c.hangupCause=field(line,'hangupCause')??c.hangupCause
 const e=voiceEvent(line,i+1);if(e)c.events.push(e);m.set(activeId,c)})
 return [...m.values()].filter(c=>c.events.some(e=>['CALL_CREATED','AGENT_SEARCH','AGENT_BOOKED','ROUTE_TO_AGENT','AGENT_RINGING','CALL_CONNECTED','CALL_DISCONNECTED','CALL_HOLD'].includes(e.type))).map(c=>{c.events.sort((a,b)=>(a.timestampMs??9e15)-(b.timestampMs??9e15)||a.lineNumber-b.lineNumber);const searches=c.events.filter(e=>e.type==='AGENT_SEARCH');c.agentSearchAttempts=searches.length;c.agentSearchDurationSeconds=searches.length>1?Math.round(((searches.at(-1)?.timestampMs??0)-(searches[0].timestampMs??0))/1000):0;c.agentSearchStart=searches[0]?.timestamp;c.agentSearchEnd=searches.at(-1)?.timestamp;const booked=c.events.some(e=>e.type==='AGENT_BOOKED'),connected=c.events.some(e=>e.type==='CALL_CONNECTED')||!!c.talkStart;c.routingStatus=connected?'Successful':booked?'Agent Booked':searches.length?'Not Reached':'Unknown';c.callStatus=connected&&(c.events.some(e=>e.type==='CALL_DISCONNECTED')||c.talkEnd)?'Completed':connected?'Connected':c.routingStatus==='Not Reached'?'Not Routed':'Unknown';c.problemScore=c.routingStatus==='Not Reached'?80:c.events.some(e=>e.type==='ERROR')?50:c.agentSearchDurationSeconds>60?20:0;c.finding=connected?`The call was successfully routed${c.agentId?` to Agent ${c.agentId}`:''}${c.extension?` / Extension ${c.extension}`:''}.`:`eFrontVoice searched for an available Agent ${searches.length} times, but no successful Agent booking or connection was detected.`;c.conclusion=connected?'No routing failure was detected for this call.':'No Agent route was confirmed before the available call events ended.';return c})}

export function analyzeVoiceExtensions(records:string[]):VoiceExtensionAnalysis[]{const ids=new Set<string>();records.forEach(l=>{const patterns=[/AGT\|LOGIN\|[^|]+\|[^|]*\|\d+\|(\d+)/i,/LOGIN(?:ACK)?_RSP\|(?:OK|FAIL)\|(\d+)/i,/SIP\|REG\|(\d+)/i,/exten=['"](\d+)/i,/REAL AGENT\s*:\s*(\d+)/i,/Device\s+(\d+)\s+monitored/i];for(const pattern of patterns){const found=l.match(pattern)?.[1];if(found)ids.add(found)}});return [...ids].map(extension=>{const lines=records.filter(l=>l.includes(extension));const login=/LOGIN_RSP\|OK|LOGINACK_RSP\|OK/i.test(lines.join('\n'));const webrtc=/SIP\|REG|loginWebRTCRegOnly|startMonitorWebRtc|monitored webrtc/i.test(lines.join('\n'));const pbxDown=/isPbxDisconnected:\s*true/i.test(lines.at(-1)??'');const warningLines=lines.filter(l=>/agentTerminalNotReady\(\).*ignored/i.test(l));const recovered=warningLines.length>0&&lines.some(l=>/REAL AGENT|Incoming call|Call connected/i.test(l));const states=lines.flatMap(l=>[...l.matchAll(/statustext=['"]([^'"]+)/gi)].map(x=>x[1]));const calls=lines.filter(l=>/Call connected/i.test(l)).length;const agentId=lines.map(l=>l.match(/AGT\|LOGIN\|[^|]+\|[^|]*\|(\d+)\|\d+/i)?.[1]??l.match(/UPDATECALLTRANSACTION\|(\d+)\|/i)?.[1]).find(Boolean);return{extension,agentId,extensionStatus:(pbxDown?'Failed':login&&webrtc?'Healthy':warningLines.length?'Warning':'Unknown') as VoiceExtensionAnalysis['extensionStatus'],pbxStatus:pbxDown?'Disconnected':'Connected',loginStatus:login?'Logged In':'Unknown',registrationStatus:webrtc?'Registered':'Unknown',monitoringStatus:/startMonitorWebRtc|monitored webrtc/i.test(lines.join('\n'))?'Active':/stopMonitor|terminalListenerEnded/i.test(lines.join('\n'))?'Stopped':'Unknown',currentState:states.at(-1)??'Unknown',callsHandled:calls,warnings:warningLines.length,unrecoveredErrors:pbxDown?1:0,recoveredWarning:recovered,finding:recovered?`A transient terminal-not-ready event was ignored; later activity confirms Extension ${extension} remained operational.`:pbxDown?'The latest evidence reports that the PBX is disconnected.':`Extension ${extension} activity was detected.`,conclusion:pbxDown?'A persistent PBX connectivity problem is present in the latest evidence.':login&&webrtc?'No persistent Extension failure was detected from the available log evidence.':'The available evidence is insufficient to confirm full Extension health.',events:lines.map((l,i)=>({timestamp:parseIvrTimestamp(l)?.timestamp,label:/agentTerminalNotReady/i.test(l)?'Terminal Not Ready (Ignored)':/Call connected/i.test(l)?'Call Connected':/LOGIN/i.test(l)?'Agent Login':'Extension Activity',rawLine:l,lineNumber:i+1})),problemScore:pbxDown?100:recovered?10:0}}).sort((a,b)=>b.problemScore-a.problemScore||a.extension.localeCompare(b.extension,undefined,{numeric:true}))}
