import { parseIvrTimestamp } from './ivrAnalyzer'
import type { VoiceCall, VoiceEvent, VoiceExtensionAnalysis } from './types'

export function normalizeEfrontVoiceRecords(text:string){return text.split(/\r?\n|(?=\d{4}-\d{2}-\d{2}\s+\d{2}:\d{2}:\d{2},\d{3})/).map(x=>x.trim()).filter(Boolean)}
function field(line:string,name:string){return line.match(new RegExp(`\\b${name}\\s*[=:]\\s*['"]?([^,}\\s'"]+)`,'i'))?.[1]}
function caller(line:string){return line.match(/\[\d{8,}\]\s*\[\d+\]\s*\[(\d{7,})\]/)?.[1]??field(line,'callerid')??line.match(/caller id\s*:\s*(\d{7,})/i)?.[1]}
function callId(line:string){return line.match(/\[(\d{12,})\]\s*\[\d+\]\s*\[\d{7,}\]/)?.[1]??field(line,'callid')}
function voiceEvent(line:string,n:number):VoiceEvent|undefined{const p=parseIvrTimestamp(line);const base={timestamp:p?.timestamp,timestampMs:p?.timestampMs,lineNumber:n,rawLine:line}
 const make=(type:VoiceEvent['type'],label:string)=>({...base,type,label})
 if(/addCallTransaction|addTransaction\(\).*inserted/i.test(line))return make('CALL_CREATED','Call Transaction Created')
 if(/CONFIRMAGTBOOKING_RSP\|OK/i.test(line))return make('AGENT_BOOKED','Agent Booking Confirmed')
 if(/GETAVAILAGT|getAvailableAgent/i.test(line))return make('AGENT_SEARCH','Searching for available Agent')
 if(/UPDATECALLTRANSACTION|agentExtension\s*:/i.test(line))return make('ROUTE_TO_AGENT','Route to Agent')
 if(/ExtensionStatusEvent.*Ringing|statustext=['"]Ringing|DialEvent|connectionAlerting|Incoming call/i.test(line))return make('AGENT_RINGING','Agent Ringing')
 if(/connectionEstablished|Call connected|callConnected\(|talkstart=(?!null)/i.test(line))return make('CALL_CONNECTED','Call Connected')
 if(/callDisconnected\(|talkend=(?!null)/i.test(line))return make('CALL_DISCONNECTED','Call Disconnected')
 if(/MusicOnHoldEvent|calculated hold duration/i.test(line))return make('CALL_HOLD','Call Hold')
 if(/ERROR|Exception/i.test(line))return make('ERROR','Error')
}
export function extractVoiceTransactionIds(records:string[]):string[]{const ids=new Set<string>();for(const line of records){for(const match of line.matchAll(/\bTID\s*:\s*(\d+)\b/gi))ids.add(match[1])}return [...ids]}
function explicitTid(line:string){return line.match(/\bTID\s*:\s*(\d+)\b/i)?.[1]}
function supportingObjectId(line:string){return line.match(/(?:[,{]\s*)id\s*=\s*(\d+)/i)?.[1]}
function mergeVoiceCall(target:VoiceCall,source:VoiceCall){target.callerId=target.callerId||source.callerId;target.callId=target.callId==='Not detected'?source.callId:target.callId;target.events.push(...source.events);for(const key of ['campaignId','agentGroupId','agentId','extension','routeStart','routeEnd','talkStart','talkEnd','hangupCause'] as const)target[key]??=source[key]}
export function analyzeVoiceCalls(records:string[]):VoiceCall[]{
 const authoritativeTids=new Set(extractVoiceTransactionIds(records));const callToTid=new Map<string,string>()
 for(const line of records){const lineCall=callId(line);const tid=explicitTid(line)??(authoritativeTids.has(supportingObjectId(line)??'')?supportingObjectId(line):undefined);if(lineCall&&tid)callToTid.set(lineCall,tid)}
 const calls=new Map<string,VoiceCall>();let activeKey:string|undefined,activeCaller:string|undefined
 records.forEach((line,index)=>{const lineCall=callId(line);const tid=explicitTid(line)??(lineCall?callToTid.get(lineCall):undefined)??(authoritativeTids.has(supportingObjectId(line)??'')?supportingObjectId(line):undefined);const explicitKey=tid?`tid:${tid}`:lineCall?`call:${lineCall}`:undefined;activeKey=explicitKey??activeKey;activeCaller=caller(line)??activeCaller;if(!activeKey||!activeCaller)return
  const current=calls.get(activeKey)??{callerId:activeCaller,callId:lineCall??'Not detected',transactionId:tid,events:[],agentSearchAttempts:0,routingStatus:'Unknown',callStatus:'Unknown',problemScore:0};current.callerId=caller(line)??current.callerId;if(lineCall&&current.callId==='Not detected')current.callId=lineCall;if(tid)current.transactionId=tid
  current.campaignId=field(line,'campaignid')??line.match(/campaign\s*:\s*(\d+)/i)?.[1]??current.campaignId;current.agentGroupId=line.match(/agent group\s*:\s*(\d+)/i)?.[1]??current.agentGroupId;current.agentId=field(line,'agentid')??line.match(/UPDATECALLTRANSACTION\|(\d+)\|/i)?.[1]??current.agentId;current.extension=line.match(/CONFIRMAGTBOOKING_RSP\|OK\|(\d+)/i)?.[1]??line.match(/UPDATECALLTRANSACTION\|\d+\|(\d+)/i)?.[1]??field(line,'deviceno')??field(line,'agentExtension')??current.extension
  current.routeStart=field(line,'routestart')??current.routeStart;current.routeEnd=field(line,'routeend')??current.routeEnd;current.talkStart=field(line,'talkstart')??current.talkStart;current.talkEnd=field(line,'talkend')??current.talkEnd;current.hangupCause=field(line,'hangupCause')??current.hangupCause;const event=voiceEvent(line,index+1);if(event)current.events.push(event);calls.set(activeKey,current)})
 // A supporting call may have been seen before its authoritative TID alias.
 for(const [call,tid] of callToTid){const callKey=`call:${call}`,tidKey=`tid:${tid}`;const source=calls.get(callKey),target=calls.get(tidKey);if(source&&target){mergeVoiceCall(target,source);calls.delete(callKey)}else if(source){source.transactionId=tid;calls.set(tidKey,source);calls.delete(callKey)}}
 return [...calls.values()].filter(item=>item.events.some(event=>['CALL_CREATED','AGENT_SEARCH','AGENT_BOOKED','ROUTE_TO_AGENT','AGENT_RINGING','CALL_CONNECTED','CALL_DISCONNECTED','CALL_HOLD'].includes(event.type))).map(item=>{item.events.sort((a,b)=>(a.timestampMs??9e15)-(b.timestampMs??9e15)||a.lineNumber-b.lineNumber);const searches=item.events.filter(event=>event.type==='AGENT_SEARCH');item.agentSearchAttempts=searches.length;item.agentSearchDurationSeconds=searches.length>1?Math.round(((searches.at(-1)?.timestampMs??0)-(searches[0].timestampMs??0))/1000):0;item.agentSearchStart=searches[0]?.timestamp;item.agentSearchEnd=searches.at(-1)?.timestamp;const booked=item.events.some(event=>event.type==='AGENT_BOOKED'),connected=item.events.some(event=>event.type==='CALL_CONNECTED')||!!item.talkStart;item.routingStatus=connected?'Successful':booked?'Agent Booked':searches.length?'Not Reached':'Unknown';item.callStatus=connected&&(item.events.some(event=>event.type==='CALL_DISCONNECTED')||item.talkEnd)?'Completed':connected?'Connected':item.routingStatus==='Not Reached'?'Not Routed':'Unknown';item.problemScore=item.routingStatus==='Not Reached'?80:item.events.some(event=>event.type==='ERROR')?50:(item.agentSearchDurationSeconds??0)>60?20:0;item.finding=connected?`The call was successfully routed${item.agentId?` to Agent ${item.agentId}`:''}${item.extension?` / Extension ${item.extension}`:''}.`:`eFrontVoice searched for an available Agent ${searches.length} times, but no successful Agent booking or connection was detected.`;item.conclusion=connected?'No routing failure was detected for this call.':'No Agent route was confirmed before the available call events ended.';return item})}


export function analyzeVoiceExtensions(records:string[]):VoiceExtensionAnalysis[]{const ids=new Set<string>();records.forEach(l=>{const patterns=[/AGT\|LOGIN\|[^|]+\|[^|]*\|\d+\|(\d+)/i,/LOGIN(?:ACK)?_RSP\|(?:OK|FAIL)\|(\d+)/i,/SIP\|REG\|(\d+)/i,/exten=['"](\d+)/i,/REAL AGENT\s*:\s*(\d+)/i,/Device\s+(\d+)\s+monitored/i];for(const pattern of patterns){const found=l.match(pattern)?.[1];if(found)ids.add(found)}});return [...ids].map(extension=>{const lines=records.filter(l=>l.includes(extension));const login=/LOGIN_RSP\|OK|LOGINACK_RSP\|OK/i.test(lines.join('\n'));const webrtc=/SIP\|REG|loginWebRTCRegOnly|startMonitorWebRtc|monitored webrtc/i.test(lines.join('\n'));const pbxDown=/isPbxDisconnected:\s*true/i.test(lines.at(-1)??'');const warningLines=lines.filter(l=>/agentTerminalNotReady\(\).*ignored/i.test(l));const recovered=warningLines.length>0&&lines.some(l=>/REAL AGENT|Incoming call|Call connected/i.test(l));const states=lines.flatMap(l=>[...l.matchAll(/statustext=['"]([^'"]+)/gi)].map(x=>x[1]));const calls=lines.filter(l=>/Call connected/i.test(l)).length;const agentId=lines.map(l=>l.match(/AGT\|LOGIN\|[^|]+\|[^|]*\|(\d+)\|\d+/i)?.[1]??l.match(/UPDATECALLTRANSACTION\|(\d+)\|/i)?.[1]).find(Boolean);return{extension,agentId,extensionStatus:(pbxDown?'Failed':login&&webrtc?'Healthy':warningLines.length?'Warning':'Unknown') as VoiceExtensionAnalysis['extensionStatus'],pbxStatus:pbxDown?'Disconnected':'Connected',loginStatus:login?'Logged In':'Unknown',registrationStatus:webrtc?'Registered':'Unknown',monitoringStatus:/startMonitorWebRtc|monitored webrtc/i.test(lines.join('\n'))?'Active':/stopMonitor|terminalListenerEnded/i.test(lines.join('\n'))?'Stopped':'Unknown',currentState:states.at(-1)??'Unknown',callsHandled:calls,warnings:warningLines.length,unrecoveredErrors:pbxDown?1:0,recoveredWarning:recovered,finding:recovered?`A transient terminal-not-ready event was ignored; later activity confirms Extension ${extension} remained operational.`:pbxDown?'The latest evidence reports that the PBX is disconnected.':`Extension ${extension} activity was detected.`,conclusion:pbxDown?'A persistent PBX connectivity problem is present in the latest evidence.':login&&webrtc?'No persistent Extension failure was detected from the available log evidence.':'The available evidence is insufficient to confirm full Extension health.',events:lines.map((l,i)=>({timestamp:parseIvrTimestamp(l)?.timestamp,label:/agentTerminalNotReady/i.test(l)?'Terminal Not Ready (Ignored)':/Call connected/i.test(l)?'Call Connected':/LOGIN/i.test(l)?'Agent Login':'Extension Activity',rawLine:l,lineNumber:i+1})),problemScore:pbxDown?100:recovered?10:0}}).sort((a,b)=>b.problemScore-a.problemScore||a.extension.localeCompare(b.extension,undefined,{numeric:true}))}
