import { describe, expect, it } from 'vitest'
import { analyzeVoicemail } from './voicemailAnalyzer'
import { analyzeLog } from './analyzer'
import part1 from './test/fixtures/voicemail-part1.log?raw'
import part2 from './test/fixtures/voicemail-part2.log?raw'

const line=(id:string,message:string,time='13:18:52')=>`[2026-08-14 ${time}] VERBOSE[4100][${id}] app_voicemail.c: ${message}`

describe('Asterisk/PBX voicemail analyzer',()=>{
 it('correlates multiple files and explains a zero-second abandoned recording',()=>{const [call]=analyzeVoicemail(`${part1}\n${part2}`);expect(call).toMatchObject({callId:'C-000aec23',mailbox:'22655001',context:'default',outcome:'No voicemail saved',classification:'Caller or upstream channel disconnected during voicemail recording',confidence:'High',recordingDurationSeconds:0,minimumDurationSeconds:1});expect(call.rootCause).toMatch(/upstream SIP channel disconnected.*0 seconds.*minimum duration/is);expect(call.finding).toBe('The voicemail system operated normally, but no message appeared because the caller channel disconnected immediately after recording began. The recording duration was 0 seconds, so Asterisk abandoned it.');expect(call.events.map(event=>event.type)).toEqual(['ROUTED','GREETING','BEEP','RECORDING_STARTED','DISCONNECTED','DURATION','ABANDONED']);expect(call.recommendedActions.join(' ')).toContain('pjsip set logger on')})
 it('runs through the explicit voicemail log type without invoking unrelated result modules',()=>{const result=analyzeLog(`${part1}\n${part2}`,'voicemail.log',2000,'asterisk-voicemail');expect(result.voicemailCalls).toHaveLength(1);expect(result.asteriskIvrCalls).toEqual([]);expect(result.agents).toEqual([])})
 it('classifies a nonzero recording below the minimum duration',()=>{const [call]=analyzeVoicemail([line('C-1','VoiceMail("PJSIP/a-1", "100@default")'),line('C-1','Recording the message'),line('C-1','Recording was 2 seconds long but needs to be at least 3 - abandoning')].join('\n'));expect(call.classification).toBe('Recording too short and abandoned');expect(call.recordingDurationSeconds).toBe(2)})
 it('recognizes a successful saved voicemail',()=>{const [call]=analyzeVoicemail([line('C-2','VoiceMail("PJSIP/a-2", "101@default")'),line('C-2','Recording the message'),line('C-2','Recording was 12 seconds long'),line('C-2','Voicemail message successfully saved')].join('\n'));expect(call.outcome).toBe('Voicemail saved successfully');expect(call.classification).toBe('Valid voicemail saved successfully')})
 it('distinguishes caller disconnect before the beep and recording',()=>{const [call]=analyzeVoicemail([line('C-3','VoiceMail("PJSIP/a-3", "102@default")'),line('C-3','User hung up on PJSIP/a-3')].join('\n'));expect(call.classification).toBe('Caller hung up before recording');expect(call.rootCause).toMatch(/before the voicemail beep/)})
 it('detects a missing mailbox',()=>{const [call]=analyzeVoicemail([line('C-4','VoiceMail("PJSIP/a-4", "103@default")'),line('C-4','Mailbox 103 does not exist')].join('\n'));expect(call.outcome).toBe('Mailbox configuration problem')})
 it.each([['Permission denied while unable to write voicemail file','Voicemail file permission or write error'],['write failed: No space left on device','Voicemail storage is full']])('detects storage failure: %s',(message,label)=>{const [call]=analyzeVoicemail([line('C-5','VoiceMail("PJSIP/a-5", "104@default")'),line('C-5',message)].join('\n'));expect(call.outcome).toBe('Storage or permission problem');expect(call.events.some(event=>event.label===label)).toBe(true)})
 it('detects a confirmed voicemail application error',()=>{const [call]=analyzeVoicemail([line('C-6','VoiceMail("PJSIP/a-6", "106@default")'),line('C-6','ERROR voicemail application error')].join('\n'));expect(call.outcome).toBe('Voicemail application error');expect(call.confidence).toBe('High')})
 it('keeps the same caller in separate call IDs',()=>{const calls=analyzeVoicemail([line('C-10','CALLERID(num)=6599999999 VoiceMail("PJSIP/a-10", "110@default")'),line('C-10','User hung up'),line('C-11','CALLERID(num)=6599999999 VoiceMail("PJSIP/a-11", "111@default")'),line('C-11','Voicemail message successfully saved')].join('\n'));expect(calls).toHaveLength(2);expect(new Set(calls.map(call=>call.callId))).toEqual(new Set(['C-10','C-11']));expect(calls.find(call=>call.callId==='C-11')?.outcome).toBe('Voicemail saved successfully')})
 it('correlates Local channel pairs without requiring the same worker thread',()=>{const [call]=analyzeVoicemail(`[2026-08-14 13:00:00] VERBOSE[1][C-20] VoiceMail("Local/120@default;1", "120@default")\n[2026-08-14 13:00:01] VERBOSE[2] Local/120@default;2 Playing 'beep.slin'`);expect(call.callId).toBe('C-20');expect(call.events.map(event=>event.type)).toContain('BEEP')})
 it('returns Inconclusive for incomplete logs',()=>{const [call]=analyzeVoicemail(line('C-12','VoiceMail("Local/112@default;1", "112@default")'));expect(call.outcome).toBe('Inconclusive');expect(call.classification).toBe('Unknown cause due to incomplete logs')})
})
