import { describe,expect,it } from 'vitest'
import healthy from './test/fixtures/webhook-healthy.log?raw'
import { analyzeWebhook, isWebhookLog, maskWebhookRecord, normalizeWebhookRecords } from './webhookAnalyzer'

describe('OpsCentral Webhook messaging flow',()=>{
 it('parses the healthy acceptance flow',()=>{const [trx]=analyzeWebhook(healthy);expect(trx).toMatchObject({trxId:'4125',maskedCustomer:'6598175528',messageIds:['39847','39849'],startNode:'532',blacklistResult:'Passed',operationHours:'Open',selectedOption:'General Enquiry',agentGroupId:'1',status:'Successfully Routed',timeoutIndicators:[],errors:[]});expect(trx.nodeJourney.map(node=>node.id)).toEqual(['532','533','538','688','544']);expect(trx.processingDurationMs).toBe(19185)})
 it('detects webhook markers and ignores shell noise',()=>{const rows=normalizeWebhookRecords(healthy);expect(rows.some(row=>row.startsWith('sh-4.4$'))).toBe(false);expect(isWebhookLog(rows)).toBe(true)})
 it('splits joined records',()=>{const joined='2026-08-10 10:00:00,000 INFO [TRX: 1] IVR_NODE_START NodeId: 1null2026-08-10 10:00:01,000 INFO [TRX: 1] IVR_NODE_ROUTE NodeId: 2';expect(normalizeWebhookRecords(joined)).toHaveLength(2)})
 it('keeps multiple TRX IDs separate even for one customer',()=>{const text='2026-08-10 10:00:00,000 INFO [TRX: 1] Setting isBlackList as 0 for 6598175528 IVR_NODE_START NodeId: 1\n2026-08-10 10:01:00,000 INFO [TRX: 2] Setting isBlackList as 0 for 6598175528 IVR_NODE_START NodeId: 1';const result=analyzeWebhook(text);expect(result.map(x=>x.trxId).sort()).toEqual(['1','2']);expect(result.every(x=>x.customerNumber==='6598175528')).toBe(true)})
 it('does not treat false and zero timeout fields as timeout',()=>{expect(analyzeWebhook(healthy)[0].status).toBe('Successfully Routed')})
 it('detects a confirmed timeout',()=>{const [trx]=analyzeWebhook('2026-08-10 10:00:00,000 INFO [TRX: 3] IVR_NODE_START NodeId: 1 pendingInputOrTimeout=true');expect(trx.status).toBe('Timeout')})
 it('requires both route node and assignment for successful routing',()=>{const [trx]=analyzeWebhook('2026-08-10 10:00:00,000 INFO [TRX: 4] IVR_NODE_ROUTE NodeId: 2 End node done/ Route Node');expect(trx.status).toBe('Incomplete / Unknown')})
 it('masks credentials and message content while retaining customer numbers',()=>{const masked=maskWebhookRecord('apikey="MwPc1234567890Wds" Customer 6598175528 Message: secret text','6598175528');expect(masked).not.toContain('MwPc1234567890Wds');expect(masked).toContain('6598175528');expect(masked).not.toContain('secret text');expect(masked).not.toContain('6598****28');expect(masked).toContain('Message: [MASKED]')})
 it('does not detect unrelated logs',()=>expect(analyzeWebhook('2026-08-10 10:00:00,000 ordinary application line')).toEqual([]))
 it('ignores harmless error property names with false values',()=>{const [trx]=analyzeWebhook(`2026-08-10 10:00:00,000 INFO [TRX: 5] IVR_NODE_START NodeId: 1 payload={"failure":false,"error":null}`);expect(trx.status).toBe('Incomplete / Unknown');expect(trx.errors).toEqual([])})

 it('deduplicates repeated grep records by TRX, timestamp, and message',()=>{const line='2026-08-10 10:00:00,000 INFO [TRX: 7] IVR_NODE_START NodeId: 1';const [trx]=analyzeWebhook(`${line}\n${line}`);expect(trx.evidence).toHaveLength(1)})
 it('sorts internally by milliseconds while sanitized records omit them',()=>{const text='2026-08-10 10:00:00,900 INFO [TRX: 8] IVR_NODE_ROUTE NodeId: 2\n2026-08-10 10:00:00,100 INFO [TRX: 8] IVR_NODE_START NodeId: 1';const [trx]=analyzeWebhook(text);expect(trx.evidence.map(item=>item.timestampMs)).toEqual([...trx.evidence.map(item=>item.timestampMs)].sort((a,b)=>(a??0)-(b??0)));expect(trx.evidence.every(item=>!item.maskedRecord.match(/10:00:00,\d{3}/))).toBe(true)})
 it('does not label normal DEBUG and JSON activity as abnormal',()=>{const text='2026-08-10 10:00:00,000 DEBUG [TRX: 9] IVR_NODE_START NodeId: 1 JSON is {"currentPromptTimeout":0}\n2026-08-10 10:00:01,000 DEBUG [TRX: 9] current msg id is 10 and the next node is 2 looping the subsequently node Saving the next node';const [trx]=analyzeWebhook(text);expect(trx.evidence.some(item=>item.label==='Abnormal messaging-flow event')).toBe(false)})

})

describe('CallFront agent routing analysis',()=>{
 const log=(lines:string[])=>lines.map((line,index)=>`2026-08-10 10:20:${String(index).padStart(2,'0')},${index%2?'500':'000'} INFO [Thread-${index}] [WS_7#601155411633#7] [TRX: 20] ${line}`).join('\n')
 const request='sendToCallFrontServer(), sending: 100|IVR|innovax.opscentral.callfront.ivr.RoutingEntry_1769306836405|GETAVAILAGT|20|7|1|1|4|4|2|null|601155411633|false|false|0|1|0|0|0'
 it('treats start and stop without lookup as Client Stopped',()=>{const [trx]=analyzeWebhook(log(['IVR_NODE_START NodeId: 1 startClient()','stopClient()']));expect(trx.agentRouting?.finalStatus).toBe('Client Stopped');expect(trx.agentRouting?.lookupAttempts).toBe(0)})
 it('detects a valid available-agent response and lookup delay',()=>{const [trx]=analyzeWebhook(log(['IVR_NODE_START NodeId: 1 startClient()',request,'received GETAVAILAGT_RSP with agent ID: 733 Preferred Language: true Default Language: false Preferred Product: true Default Product: false']));expect(trx.agentRouting).toMatchObject({finalStatus:'Agent Found',selectedAgentId:733,lookupAttempts:1,customerNumber:'601155411633',webSocketSession:'WS_7#601155411633#7',routingEntryId:'RoutingEntry_1769306836405',agentLookupDelayMs:500})})
 it('classifies a final negative response and extracts matching results',()=>{const [trx]=analyzeWebhook(log(['IVR_NODE_START NodeId: 1',request,'received GETAVAILAGT_RSP with agent ID: -1 Preferred Language: false Default Language: false Preferred Product: false Default Product: false']));expect(trx.agentRouting).toMatchObject({finalStatus:'No Available Agent',responseAgentIds:[-1],preferredLanguage:false,defaultLanguage:false,preferredProduct:false,defaultProduct:false})})
 it('classifies a valid response after a negative retry',()=>{const [trx]=analyzeWebhook(log(['IVR_NODE_START NodeId: 1',request,'receivedGETAVAILAGT_RSP with agent ID: -1',request,'received GETAVAILAGT_RSP with agent ID: 733','stopClient()']));expect(trx.agentRouting).toMatchObject({finalStatus:'Agent Found After Retry',selectedAgentId:733,lookupAttempts:2,responseAgentIds:[-1,733]});expect(trx.agentRouting?.finding).toContain('do not confirm agent acceptance or reply')})
 it('classifies a request without response as incomplete',()=>{const [trx]=analyzeWebhook(log(['IVR_NODE_START NodeId: 1',request,'stopClient()']));expect(trx.agentRouting?.finalStatus).toBe('Incomplete Agent Routing')})
 it('supports optional whitespace after received',()=>{const compact=analyzeWebhook(log(['IVR_NODE_START NodeId: 1',request,'receivedGETAVAILAGT_RSP with agent ID: 42']))[0];expect(compact.agentRouting?.selectedAgentId).toBe(42)})
 it('treats a disconnection followed by successful continuation as recovered warning',()=>{const [trx]=analyzeWebhook(log(['IVR_NODE_START NodeId: 1',request,'disconnected(), IVR client was disconnected from callfront server, reconnecting',request,'received GETAVAILAGT_RSP with agent ID: 733']));expect(trx.agentRouting?.finalStatus).toBe('Agent Found');expect(trx.agentRouting?.connectionWarning).toContain('successful continuation')})
 it('tracks repeated disconnections and an unrecovered interruption',()=>{const [trx]=analyzeWebhook(log(['IVR_NODE_START NodeId: 1',request,'disconnected(), IVR client was disconnected from callfront server, reconnecting','disconnected(), IVR client was disconnected from callfront server, reconnecting']));expect(trx.agentRouting).toMatchObject({finalStatus:'CallFront Connection Interrupted',disconnectionCount:2})})
 it('correlates the same WebSocket session across different worker threads',()=>{const [trx]=analyzeWebhook(log(['IVR_NODE_START NodeId: 1 startClient()',request,'received GETAVAILAGT_RSP with agent ID: 733']));expect(trx.agentRouting?.events).toHaveLength(3);expect(trx.agentRouting?.webSocketSession).toBe('WS_7#601155411633#7')})
 it('extracts routing processing values without assuming a unit',()=>{const [trx]=analyzeWebhook(log(['IVR_NODE_START NodeId: 1','processRoutingEntry() == RoutingEntry process time : 290 of max: 10800']));expect(trx.agentRouting).toMatchObject({processingValue:290,maximumProcessingValue:10800});expect(trx.agentRouting?.usagePercentage).toBeCloseTo(2.685,2)})
})
