import { parseIvrTimestamp } from './ivrAnalyzer'
import type { WhatsappEvidence, WhatsappMessageAnalysis, WhatsappStatus, WhatsappTimings } from './types'

export interface WhatsappThresholds { sendToSentWarningMs:number; sentToDeliveredWarningMs:number; deliveredToReadInfoMs:number }
export const DEFAULT_WHATSAPP_THRESHOLDS:WhatsappThresholds={sendToSentWarningMs:5000,sentToDeliveredWarningMs:30000,deliveredToReadInfoMs:300000}
export const normalizeOcod5Records=(text:string)=>text.split(/\r?\n|(?=\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2},\d{3})/).map(x=>x.trim()).filter(Boolean)
const field=(line:string,names:string[])=>{for(const name of names){const match=line.match(new RegExp(`["']?${name}["']?\\s*[:=]\\s*["']?([^,"'\\s}\\]]+)`,'i'));if(match)return match[1]}return undefined}
const maskPhone=(value?:string)=>!value?'Unknown':value.length<7?'***':`${value.slice(0,4)}${'*'.repeat(Math.max(3,value.length-6))}${value.slice(-2)}`
const epoch=(value?:string)=>{if(!value)return undefined;const numeric=Number(value);if(Number.isFinite(numeric))return numeric<1e12?numeric*1000:numeric;const parsed=Date.parse(value);return Number.isNaN(parsed)?undefined:parsed}
const elapsed=(events:WhatsappEvidence[],from:WhatsappEvidence['type'],to:WhatsappEvidence['type'])=>{const a=events.find(e=>e.type===from)?.timestampMs;const b=events.find(e=>e.type===to)?.timestampMs;return a!==undefined&&b!==undefined&&b>=a?b-a:undefined}
export function analyzeOcod5Whatsapp(text:string,thresholds:WhatsappThresholds=DEFAULT_WHATSAPP_THRESHOLDS):WhatsappMessageAnalysis[]{
 const records=normalizeOcod5Records(text);if(!records.some(line=>/WhatsAppSendingThread|\[AliCloud\]\s*Sending WA message|WhatsAppWebhook|"NoticeType"\s*:\s*"inbound"|"Status"\s*:\s*"(?:Sent|Delivered|Read)"/i.test(line)))return[]
 type Row={line:string;lineNumber:number;messageId?:string;taskId?:string;conversationId?:string};const rows:Row[]=records.map((line,index)=>({line,lineNumber:index+1,messageId:field(line,['MessageId','messageId']),taskId:field(line,['TaskId','taskId']),conversationId:field(line,['ConversationId','conversationId'])}))
 const aliases=new Map<string,string>();for(const row of rows){const key=row.messageId??row.taskId;if(!key)continue;if(row.messageId)aliases.set(`m:${row.messageId}`,key);if(row.taskId)aliases.set(`t:${row.taskId}`,key)}
 const groups=new Map<string,Row[]>();let active:string|undefined;for(const row of rows){const key=(row.messageId&&aliases.get(`m:${row.messageId}`))??(row.taskId&&aliases.get(`t:${row.taskId}`))??active;if(!key)continue;active=key;const list=groups.get(key)??[];list.push(row);groups.set(key,list)}
 const analyses=[...groups.entries()].map(([key,group])=>{const events:WhatsappEvidence[]=[];let duplicateCallbacks=0;const seenStatuses=new Set<string>();const errors:string[]=[];let direction:'Inbound'|'Outbound'|'Unknown'='Unknown'
  for(const row of group){const p=parseIvrTimestamp(row.line);const provider=epoch(field(row.line,['Timestamp','EventTime','Time']));const push=(type:WhatsappEvidence['type'],label:string,duplicate=false)=>events.push({timestamp:p?.timestamp,timestampMs:p?.timestampMs,providerTimestampMs:provider,lineNumber:row.lineNumber,type,label,rawLine:row.line,duplicate})
   if(/"NoticeType"\s*:\s*"inbound"/i.test(row.line)){direction='Inbound';push('INBOUND','Inbound customer message received')}
   if(/WhatsAppSendingThread/i.test(row.line)&&/send|prepar/i.test(row.line)){direction='Outbound';push('SEND_ATTEMPT','Outbound send prepared')}
   if(/\[AliCloud\]\s*Sending WA message/i.test(row.line)){direction='Outbound';push('PROVIDER_SUBMISSION','Message submitted to provider')}
   for(const status of ['Sent','Delivered','Read'] as const){if(new RegExp(`["']?Status["']?\\s*:\\s*["']${status}["']`,'i').test(row.line)){direction='Outbound';const dedupe=seenStatuses.has(status);if(dedupe)duplicateCallbacks++;else seenStatuses.add(status);push(status.toUpperCase() as WhatsappEvidence['type'],dedupe?`Duplicate ${status} callback`:`${status} callback received`,dedupe)}}
   if(/\b(?:ERROR|Exception|authentication failed|unauthorized|rate limit|template .*error|session window|media .*error|send failed|delivery failed)\b|["']Status["']\s*:\s*["']Failed["']/i.test(row.line)){errors.push(row.line);push('FAILURE','WhatsApp processing failure')}
  }
  events.sort((a,b)=>(a.timestampMs??Number.MAX_SAFE_INTEGER)-(b.timestampMs??Number.MAX_SAFE_INTEGER)||a.lineNumber-b.lineNumber);const statuses=['Sent','Delivered','Read'].filter(s=>seenStatuses.has(s));const status:WhatsappStatus=errors.length?'Send/delivery failed':direction==='Inbound'?'Inbound message received':seenStatuses.has('Read')?'Delivered and read':seenStatuses.has('Delivered')?'Delivered, awaiting read':seenStatuses.has('Sent')?'Sent, awaiting delivery':'Pending / incomplete evidence'
  const timings:WhatsappTimings={sendToSentMs:elapsed(events,events.some(e=>e.type==='PROVIDER_SUBMISSION')?'PROVIDER_SUBMISSION':'SEND_ATTEMPT','SENT'),sentToDeliveredMs:elapsed(events,'SENT','DELIVERED'),deliveredToReadMs:elapsed(events,'DELIVERED','READ'),webhookLagMs:events.filter(e=>e.providerTimestampMs!==undefined&&e.timestampMs!==undefined).map(e=>Math.max(0,e.timestampMs!-e.providerTimestampMs!))[0]};const warnings:string[]=[];if(timings.sendToSentMs!==undefined&&timings.sendToSentMs>thresholds.sendToSentWarningMs)warnings.push('Send acknowledgement exceeded the configured threshold.');if(timings.sentToDeliveredMs!==undefined&&timings.sentToDeliveredMs>thresholds.sentToDeliveredWarningMs)warnings.push('Delivery acknowledgement exceeded the configured threshold.');if(duplicateCallbacks)warnings.push(`${duplicateCallbacks} duplicate status callback${duplicateCallbacks===1?' was':'s were'} ignored.`)
  const joined=group.map(r=>r.line).join('\n');const customer=direction==='Inbound'?field(joined,['From','customerNumber','PhoneNumber']):field(joined,['to','customerNumber','PhoneNumber']);const business=direction==='Inbound'?field(joined,['To','businessNumber']):field(joined,['from','businessNumber']);const messageId=group.map(r=>r.messageId).find(Boolean);const taskId=group.map(r=>r.taskId).find(Boolean);const finding=status==='Delivered and read'?'The outbound WhatsApp message was sent, delivered, and read.':status==='Inbound message received'?'An inbound customer WhatsApp message was received.':status==='Send/delivery failed'?'A confirmed WhatsApp send or delivery error was detected.':`The WhatsApp message is ${status.toLowerCase()}; this is not by itself a failure.`;return{key,conversationId:field(joined,['ConversationId']),messageId,taskId,transactionId:field(joined,['trxId','transactionId']),campaignId:field(joined,['campaignId']),customerNumber:customer,maskedCustomer:maskPhone(customer),businessNumber:business,maskedBusiness:maskPhone(business),wabaId:field(joined,['WabaId','WABAID']),userId:field(joined,['UserId']),direction,messageType:field(joined,['MessageType','MsgType']),conversationType:field(joined,['ConversationType']),contextualReplyId:field(joined,['ContextMessageId','ContextId']),status,statusProgression:statuses,duplicateCallbacks,warnings,errors,timings,events,finding,problemScore:errors.length?100:status==='Pending / incomplete evidence'?40:warnings.length?20:0} satisfies WhatsappMessageAnalysis})
 for(const outbound of analyses.filter(item=>item.direction==='Outbound'&&item.conversationId)){const inbound=analyses.filter(item=>item.direction==='Inbound'&&item.conversationId===outbound.conversationId).flatMap(item=>item.events).filter(event=>event.type==='INBOUND'&&(event.timestampMs??Infinity)<(outbound.events[0]?.timestampMs??-1)).at(-1);const response=outbound.events.find(event=>event.type==='SEND_ATTEMPT'||event.type==='PROVIDER_SUBMISSION');if(inbound?.timestampMs!==undefined&&response?.timestampMs!==undefined)outbound.timings.inboundToResponseMs=response.timestampMs-inbound.timestampMs}
 return analyses.sort((a,b)=>b.problemScore-a.problemScore||(b.events[0]?.timestamp??'').localeCompare(a.events[0]?.timestamp??''))
}
